### ISSUE TITLE
Feature Request: Filtering by tag value

### ISSUE THREAD

**Issue by tksh164** [kzk839/aprl-kql-workbook#3]
Sometimes we need to identify resources by tag instead of entire subscription.

I know that the following proposed implementation may increase maintenance efforts due to the gap from APRL queries. But tag filtering will provide better resource selecting capability with large/complex subscriptions.

Proposing implementation:

1. Add parameters to select a tag to filter resources.

    `TagName` parameter

    ```
    resources
    | where tags != "" and tags != "[]"
    | mvexpand tags
    | extend tagName = tostring(bag_keys(tags)[0])
    | distinct tagName
    | sort by tagName asc
    ```

    `TagValue` parameter

    ```
    resources
    | mvexpand tags
    | extend tagName = tostring(bag_keys(tags)[0])
    | extend tagValue = tostring(tags[tagName])
    | where tags != "" and tags != "[]" and tostring(bag_keys(tags)[0]) == "{TagName}"
    | distinct tagValue
    | sort by tagValue asc
    ```

2. Add `join` operator to every query in the workbook to filter resources by selected tag. The following is an example in Key Vault.

    Current query (original APRL query)

    ```
    resources
    | where type == "microsoft.keyvault/vaults"
    | where isnull(properties.enableSoftDelete) or properties.enableSoftDelete != "true"
    | project recommendationId = "kv-1", name, id, tags, softDeleteEnabled = "disabled"
    ```

    Query after added `join` operator

    ```
    resources
    | where type == "microsoft.keyvault/vaults"
    | join kind = innerunique(
        resources
        | extend replaced_tags = replace("{}", "null", tostring(tags))
        | extend replaced_tags = parse_json(replaced_tags)
        | mv-expand replaced_tags
        | extend tagName = tostring(bag_keys(replaced_tags)[0])
        | extend tagValue = tostring(replaced_tags['{TagName}'])
        | where tagName has "{TagName}" and tagValue has "{TagValue}"
        | distinct id
        )
        on id
    | where isnull(properties.enableSoftDelete) or properties.enableSoftDelete != "true"
    | project recommendationId = "kv-1", name, id, tags, softDeleteEnabled = "disabled"
    ```

**Comment by kzk839** [comment]
Thank you for your good feedback and patience.

We have created a Workbook that can be filtered by resource groups and tags as well as subscriptions.

Currently, APRL is updated very quickly, so the filtered version, which requires modifications to the query, may be slow to reflect updates.
For this reason, we are currently separating a simple Workbook without filters and Workbook with filters.

Please use the Workbook with the file name APRL_QueriesBook_Filter.workbook.
